### ISSUE TITLE
Is the project dead?

### ISSUE THREAD

**Issue by erlanger** [Web-Prolog/swi-web-prolog#6]
I noticed the project has not been updated in a while, and that issues from months ago have no comments. 

Is the project dead? I hope someone revives it.

**Comment by torbjornlager** [comment]
No, it isn't dead, just resting. :-) 

I'm currently trying to figure out where I want this project to go, mostly concentrating on the book rather than on coding at the moment.

Feel free write to me at torbjorn.lager@gmail.com if you have comments/ideas pertaining to the book or the PoC implementation. I could surely use some help.
